### ISSUE TITLE
dial tcp: lookup port=0: no such host

### ISSUE THREAD

**Issue by tonylu0728** [barats/RepoStats#1]
拉取公开latest镜像 run执行后 会报dial tcp: lookup port=0: no such host

**Comment by barats** [comment]
> 拉取公开latest镜像 run执行后 会报dial tcp: lookup port=0: no such host

启动的时候，需要指定配置文件才可以。

```
[repostats]
debug = false
admin_port = 9103


[postgres]
host = localhost
port = 15432
user = postgres
password = DePmoG_123
database = repostats
max_open_conn = 20
max_idle_conn = 5

[grafana]
host = localhost
port = 13000
user = admin
password = admin
Footer

```

镜像启动需要依赖 Grafana 和 Postgresql 数据库，而且还需要有指定的配置文件。

完整的 compose 文件可以参考： https://github.com/barats/RepoStats/blob/main/docker/pull_build.yml
